version: '1'
services:
  backend:
    env_file:
        "./server/server.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "mauriciolom/cerebral-game-test-server"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "mauriciolom/cerebral-game-test-client"
    ports:
      - "3000:3000"
    links:
      - "backend"