version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "mauriciolom/cerebral-game-test-server"
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    image: "mauriciolom/cerebral-game-test-web"
    ports:
      - "3000:3000"
    links:
      - "backend"